name: Release Next Version
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        type: string
env:
  NEW_VERSION: ${{ github.event.inputs.release_tag }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PROJECT_TOKEN }}
      - name: Modify for next release
        run: |
          chmod +x release.sh
          ./release.sh ${{ env.NEW_VERSION }}
          npm i
          git diff
          git config user.name '${{ vars.USER_NAME }}'
          git config user.email '${{ vars.USER_EMAIL }}'
          git add .
          git commit -m 'release: clickstream Web ${{ env.NEW_VERSION }}'
          git push
          git tag v${{ env.NEW_VERSION }}
          git push origin v${{ env.NEW_VERSION }}
      - name: Prepare release file
        run: |
          npm i
          npm run pack
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: "Clickstream Web ${{ env.NEW_VERSION }}"
          files: |
            dist/clickstream-web.min.js
            dist/clickstream-web.min.js.map
            gtm-template/ClickstreamAnalytics-gtm-template.tpl
          tag_name: "v${{ env.NEW_VERSION }}"
          prerelease: true
          generate_release_notes: true
